export const movies = [
  {
    title: "Bullet Train",
    img: "bullet-train-movie.jpg",
    year: "2022",
    duration: "126 min",
    type: "Movie",
  },
  {
    title: "The Princess",
    img: "the-princess-movie.jpg",
    year: "2022",
    duration: "94 min",
    type: "Movie",
  },
  {
    title: "Top Gun:Maverick",
    img: "top-gun-maverick-movie-poster-6207.jpg",
    year: "2022",
    duration: "130 min",
    type: "Movie",
  },
  {
    title: "Morbius",
    img: "morbius-movie-poster-6498.jpg",
    year: "2022",
    duration: "108 min",
    type: "Movie",
  },
  {
    title: "Scream",
    img: "scream-2022-movie-poster-6686.jpg",
    year: "2022",
    duration: "126 min",
    type: "Movie",
  },
  {
    title: "Uncharted",
    img: "uncharted-movie-poster-6522.jpg",
    year: "2022",
    duration: "116 min",
    type: "Movie",
  },
  {
    title: "The Bad Guys",
    img: "the-bad-guys-movie-poster-6781.jpg",
    year: "2022",
    duration: "140 min",
    type: "Movie",
  },
  {
    title: "Thirteen Lives",
    img: "thirteen-lives-movie-poster-6992.jpg",
    year: "2022",
    duration: "142 min",
    type: "Movie",
  },
  {
    title: "Resident Evil: Welcome to Raccon City",
    img: "resident-evil-welcome-to-raccoon-city-.jpg",
    year: "2021",
    duration: "107 min",
    type: "Movie",
  },
  {
    title: "Opration Fortune:Ruse de Guerre",
    img: "operationfortune-ruse-de-guerre-movie-poster-6864.jpg",
    year: "2022",
    duration: "98 min",
    type: "Movie",
  },
  {
    title: "Clifford The big Red",
    img: "clifford-the-big-read-dog-movie-poster-6695.jpg",
    year: "2022",
    duration: "97 min",
    type: "Movie",
  },
];
